get:
  summary: Retrieve information and planets for Galaxy server
  operationId: get-galaxy
  tags:
    - galaxy

  responses:
    '200':
      description: Galaxy information
      content:
        application/json:
          schema:
            $ref: '../openapi.yaml#/components/schemas/Galaxy'

    default:
      description: unexpected error
      content:
        application/json:
          schema:
            $ref: '../openapi.yaml#/components/schemas/Error'
