type: object
required:
  - id
  - name
  - visitorEnabled
  - tycoonEnabled
  - tycoonAuthentication

properties:
  id:
    type: string
  name:
    type: string

  visitorEnabled:
    type: boolean
  tycoonEnabled:
    type: boolean

  tycoonAuthentication:
    type: string
    enum: [password]

  planets:
    type: array
    items:
      $ref: "../openapi.yaml#/components/schemas/Planet"
